name: webengage_flutter_web
description: The web implementation of webengage_flutter
homepage: https://webengage.com/
version: 2.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webengage_flutter_platform_interface:
    # path: ../webengage_flutter_platform_interface
    git:
      url: git://github.com/algirdasmac/webengage-flutter
      path: webengage_flutter_platform_interface
      ref: federated
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebEngagePlugin
        fileName: webengage_flutter_web.dart
