name: webengage_flutter
description: WebEngage Flutter plugin.
version: 2.1.12
homepage: https://webengage.com/
repository: https://github.com/WebEngage/webengage-flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  webengage_flutter_platform_interface:
    git:
      url: git://github.com/eimantas1998/webengage-flutter
      path: webengage_flutter_platform_interface
      ref: federated
  webengage_flutter_web:
    git:
      url: git://github.com/eimantas1998/webengage-flutter
      path: webengage_flutter_web
      ref: federated

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.webengage.webengage_plugin
        pluginClass: WebEngagePlugin
      ios:
        pluginClass: WebEngagePlugin
      web:
        default_package: webengage_flutter_web
